[2024-01-06T10:06:15.883+0000] {processor.py:153} INFO - Started process (PID=9221) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v5.py
[2024-01-06T10:06:15.883+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v5.py for tasks to queue
[2024-01-06T10:06:15.884+0000] {logging_mixin.py:137} INFO - [2024-01-06T10:06:15.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v5.py
[2024-01-06T10:06:15.927+0000] {logging_mixin.py:137} INFO - [2024-01-06T10:06:15.927+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v5.py", line 79, in <module>
    url = Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable csv_url does not exist'
[2024-01-06T10:06:15.928+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v5.py
[2024-01-06T10:06:15.932+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v5.py took 0.052 seconds
